# Generated by Django 3.2.3 on 2021-05-14 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('qr_code', models.FileField(upload_to='QR_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QR_app.saver')),
            ],
        ),
    ]
