# Generated by Django 3.2.3 on 2021-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0002_auto_20210514_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adress',
            field=models.CharField(default='Moscow', max_length=50),
            preserve_default=False,
        ),
    ]
