# Generated by Django 3.2.3 on 2021-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0003_person_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ManyToManyField(to='QR_app.Status'),
        ),
    ]
