# Generated by Django 3.2.3 on 2021-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0004_auto_20210514_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qr_code',
            field=models.FileField(blank=True, upload_to='QR_code'),
        ),
    ]
