# Generated by Django 3.2.3 on 2021-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0006_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
