# Generated by Django 3.2.3 on 2021-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0007_alter_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
