# Generated by Django 3.2.3 on 2021-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0008_status_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='slug',
        ),
    ]
