# Generated by Django 3.2.3 on 2021-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0009_remove_status_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(default=12),
            preserve_default=False,
        ),
    ]
