# Generated by Django 3.2.3 on 2021-05-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0011_auto_20210522_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='qwe2'),
            preserve_default=False,
        ),
    ]
