# Generated by Django 3.2.3 on 2021-05-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0012_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Act', 'Активный'), ('Dea', 'Не активный')], max_length=3),
        ),
    ]
