# Generated by Django 3.2.3 on 2021-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0013_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/QR/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Act', 'Активный'), ('Dea', 'Не активный')], default='New', max_length=3),
        ),
    ]
