# Generated by Django 3.2.3 on 2021-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0014_auto_20210525_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='person',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
