# Generated by Django 3.2.3 on 2021-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_app', '0015_auto_20210526_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='news_image/%Y/%m/%d')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
